<a href="https://colab.research.google.com/github/metarun/Mechanistic-Interpretability-Exploration/blob/main/0_Zero_Layer_Transformer.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

[0L Transformer model explaination by Chris Olah](https://www.youtube.com/watch?v=V3NQaDR3xI4)

<img src="https://raw.githubusercontent.com/metarun/images/main/0_Layer_transformer_model_1.png" width="" style="vertical-align:middle;">

0 Layer Transformer model.


<img src="https://raw.githubusercontent.com/metarun/images/main/0_Layer_transformer_model_2.png" width="" style="vertical-align:middle;">

0 Layer Transformer model.

In [ ]:
import torch
import torch.nn as nn

class ZeroLayerTransformer(nn.Module):
    def __init__(self, vocab_size, d_model):
        super().__init__()
        self.embed = nn.Embedding(vocab_size, d_model)
        self.unembed = nn.Linear(d_model, vocab_size, bias=False)

    def forward(self, tokens):
        x = self.embed(tokens)      # tokens → vectors # x = W^E token
        logits = self.unembed(x)    # vectors → vocab scores # W^U W^E token
        return logits

In [ ]:
vocab_size = 1000
d_model = 64

model = ZeroLayerTransformer(vocab_size, d_model)
tokens = torch.tensor([[1, 5, 3, 7, 2]])  # fake token ids
logits = model(tokens)
print(f"Input shape:  {tokens.shape}")
print(f"Output shape: {logits.shape}")
print(f"Prediction at last position: {logits[0, -1, :].argmax()}")

Input shape:  torch.Size([1, 5])
Output shape: torch.Size([1, 5, 1000])
Prediction at last position: 92


In [ ]:
embedded_tokens = model.embed(tokens)
print(f"Embedded tensor shape: {embedded_tokens.shape}")
print(f"Embedded tensor content (first 5 elements of first token):\n{embedded_tokens[0, 0, :5]}")

Embedded tensor shape: torch.Size([1, 5, 64])
Embedded tensor content (first 5 elements of first token):
tensor([-1.2394,  0.4175, -1.1253, -1.4859,  0.3031], grad_fn=<SliceBackward0>)


In [ ]:
raw_embeddings = model.embed.weight
print(f"Shape of raw embedding weights: {raw_embeddings.shape}")
print(f"First 5 elements of the embedding vector for token ID 0:\n{raw_embeddings[0, :5]}")
print(f"First 5 elements of the embedding vector for token ID 1:\n{raw_embeddings[1, :5]}")

Shape of raw embedding weights: torch.Size([1000, 64])
First 5 elements of the embedding vector for token ID 0:
tensor([-1.7483,  0.2973, -1.0631,  1.6799, -0.2112], grad_fn=<SliceBackward0>)
First 5 elements of the embedding vector for token ID 1:
tensor([-1.2394,  0.4175, -1.1253, -1.4859,  0.3031], grad_fn=<SliceBackward0>)


In [ ]:
raw_embeddings

Parameter containing:
tensor([[-1.7483,  0.2973, -1.0631,  ..., -0.5370,  0.8122, -1.1312],
        [-1.2394,  0.4175, -1.1253,  ...,  0.6463,  0.3157, -0.4350],
        [-1.0737, -0.2401,  0.8815,  ..., -0.2893,  0.9136,  1.1710],
        ...,
        [-0.0943,  0.1851, -0.4603,  ..., -0.1841,  0.2796, -0.1907],
        [ 0.7255, -0.8354, -0.2974,  ..., -1.3028,  0.3754,  0.7670],
        [ 1.1544, -0.3967,  1.8853,  ..., -1.7048,  0.8721,  1.4999]],
       requires_grad=True)

This `raw_embeddings` tensor has a shape of `(vocab_size, d_model)`, where each row represents the embedding vector for a specific token ID. For example, `raw_embeddings[0]` is the embedding vector for token ID 0, and `raw_embeddings[1]` is the embedding vector for token ID 1, and so on.